apiVersion: v1
kind: Namespace
metadata:
  name: touge-flux
  labels:
    owner: usama

---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: touge-flux
spec:
  releaseName: rogue-flux
  chart:
    repository: https://charts.fluxcd.io
    name: flux
    version: 1.3.0
  values:
    replicaCount: 1
    helmOperator:
      create: false
      createCRD: false
    rbac:
      create: true
    clusterRole:
      create: true
    serviceAccount:
      create: true
    memcached:
      enabled: true
      addSecurityContext: false
      securityContext: {}
    prometheus:
      enabled: true
    resources:
      limits:
        cpu: "100m"
        memory: "512Mi"
      requests:
        cpu: "50m"
        memory: "64Mi"
    registry:
      pollInterval: "1m"
    git:
      url: "ssh://git@github.com/usamaahmadkhan/togue-flux.git"
      pollInterval: "1m"
      branch: "master"
      path: "rogue-dir"
