apiVersion: v1
kind: ServiceAccount
metadata:
  name: rogue-sa
  namespace: togue-flux
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rogue-clusterbinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: rogue-sa
    namespace: togue-flux
